version: '3'
services:
    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ror2api
        restart: always

    api:
        build:
            context: ./api
            dockerfile: Dockerfile.dev
        restart: always
        env_file:
            - api.env
        volumes:
            - ./api/src:/usr/app/src
            - /usr/app/node_modules
        links:
            - 'db'
        depends_on:
            - db
        command: npm run dev

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - api
        command: nginx -g 'daemon off;'
        ports:
            - '80:80'

volumes:
    db_data: