version: '3'
services:
    db:
        image: trevorbrowndev/rainmain/db:latest
        build:
            context: ./db
            dockerfile: Dockerfile
        volumes:
            - db_data:/var/lib/postgresql/data
    api:
        image: trevorbrowndev/rainmain/api:latest
        build:
            context: ./api
            dockerfile: Dockerfile
        links:
            - 'db'
        depends_on:
            - 'db'

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - api
        command: nginx -g 'daemon off;'
        ports:
            - '80:80'
        links:
            - 'api'

volumes:
    db_data:
